"""
Content Generator Skill - 将 ArXiv 论文转化为博客文案

默认配置：
- 标题前缀: "ArXiv 大模型训推进展 - "
- 分类: "AI/大模型"
- 语言: 中文
- 写作风格: 专业（professional）
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional


@dataclass
class ArXivPaper:
    """ArXiv 论文数据结构（与 arxiv_scraper 保持一致）"""
    title: str
    authors: List[str]
    abstract: str
    arxiv_id: str
    url: str
    pdf_url: str
    submitted_date: str
    categories: List[str] = field(default_factory=list)


@dataclass
class BlogContent:
    """博客内容数据结构"""
    title: str
    summary: str
    content: str
    tags: List[str] = field(default_factory=list)
    category: str = "AI/大模型"
    created_at: str = ""


@dataclass
class GeneratorResult:
    """生成结果数据结构"""
    success: bool
    blog_content: Optional[BlogContent] = None
    error_message: str = ""


class ContentGeneratorSkill:
    """
    内容生成技能

    功能：将 ArXiv 论文数据转化为博客文案
    支持：多种写作风格、多语言输出
    """

    DEFAULT_CONFIG = {
        "title_prefix": "ArXiv 大模型训推进展 - ",
        "default_category": "AI/大模型",
        "default_language": "zh",
        "default_style": "professional",
        "max_abstract_length": 300,
        "include_pdf_link": True,
    }

    STYLE_TEMPLATES = {
        "professional": {
            "intro": "本期为您带来 ArXiv 上关于大模型训练与推理的最新研究进展。\n\n",
            "paper_intro": "## 📄 {index}. {title}\n\n",
            "author_line": "**作者**: {authors}\n\n",
            "date_line": "**发布日期**: {date}\n\n",
            "abstract_header": "**摘要**:\n\n{abstract}\n\n",
            "link_line": "**论文链接**: [{url}]({url})\n\n",
            "pdf_line": "**PDF**: [{pdf_url}]({pdf_url})\n\n",
            "category_line": "**分类**: {categories}\n\n",
            "outro": "\n---\n\n*以上论文来自 ArXiv 自动抓取，内容仅供参考。*\n",
        },
        "casual": {
            "intro": "👋 又到了大模型研究分享时间！来看看最近有哪些有趣的论文吧～\n\n",
            "paper_intro": "### {index}. {title}\n\n",
            "author_line": "📝 作者: {authors}\n\n",
            "date_line": "📅 {date}\n\n",
            "abstract_header": "💡 **摘要**: {abstract}\n\n",
            "link_line": "🔗 [查看原文]({url})\n\n",
            "pdf_line": "📥 [下载PDF]({pdf_url})\n\n",
            "category_line": "🏷️ {categories}\n\n",
            "outro": "\n---\n\n*希望这些内容对你有帮助！*\n",
        },
        "academic": {
            "intro": "# 大模型训练与推理研究进展\n\n以下为 ArXiv 最新收录的相关论文摘要。\n\n",
            "paper_intro": "## {index}. {title}\n\n",
            "author_line": "Authors: {authors}\n\n",
            "date_line": "Submitted: {date}\n\n",
            "abstract_header": "Abstract:\n\n{abstract}\n\n",
            "link_line": "arXiv: [{arxiv_id}]({url})\n\n",
            "pdf_line": "PDF: [{pdf_url}]({pdf_url})\n\n",
            "category_line": "Categories: {categories}\n\n",
            "outro": "\n---\n\n*Generated by ArXiv Blog Agent*\n",
        },
    }

    def __init__(self, config: Optional[dict] = None):
        """初始化内容生成器"""
        self.config = {**self.DEFAULT_CONFIG, **(config or {})}

    def _format_authors(self, authors: List[str]) -> str:
        """格式化作者列表"""
        if not authors:
            return "未知"
        if len(authors) <= 3:
            return ", ".join(authors)
        return f"{', '.join(authors[:3])} 等"

    def _format_categories(self, categories: List[str]) -> str:
        """格式化分类标签"""
        if not categories:
            return "未分类"
        return ", ".join(categories[:5])

    def _truncate_abstract(self, abstract: str, max_length: int = None) -> str:
        """截断摘要"""
        max_length = max_length or self.config["max_abstract_length"]
        if len(abstract) <= max_length:
            return abstract
        return abstract[:max_length].rsplit(" ", 1)[0] + "..."

    def _generate_paper_section(self, paper: ArXivPaper, index: int,
                                 style: str) -> str:
        """生成单篇论文的文案段落"""
        template = self.STYLE_TEMPLATES.get(style, self.STYLE_TEMPLATES["professional"])

        section = template["paper_intro"].format(index=index, title=paper.title)
        section += template["author_line"].format(authors=self._format_authors(paper.authors))

        if paper.submitted_date:
            section += template["date_line"].format(date=paper.submitted_date)

        section += template["abstract_header"].format(
            abstract=self._truncate_abstract(paper.abstract)
        )

        if paper.url:
            if "arxiv_id" in template["link_line"]:
                section += template["link_line"].format(
                    arxiv_id=paper.arxiv_id, url=paper.url
                )
            else:
                section += template["link_line"].format(url=paper.url)

        if self.config["include_pdf_link"] and paper.pdf_url:
            section += template["pdf_line"].format(pdf_url=paper.pdf_url)

        section += template["category_line"].format(
            categories=self._format_categories(paper.categories)
        )

        return section

    def _extract_tags(self, papers: List[ArXivPaper]) -> List[str]:
        """从论文中提取标签"""
        tags = set()
        for paper in papers:
            tags.update(paper.categories[:3])
            title_lower = paper.title.lower()
            keywords = ["transformer", "attention", "llm", "gpt", "bert",
                       "diffusion", "training", "inference", "optimization"]
            for kw in keywords:
                if kw in title_lower:
                    tags.add(kw.upper())

        return list(tags)[:10]

    def _generate_summary(self, papers: List[ArXivPaper]) -> str:
        """生成文章摘要"""
        count = len(papers)
        if count == 0:
            return "暂无论文数据。"

        categories = set()
        for paper in papers:
            categories.update(paper.categories[:2])

        return (
            f"本期收录 {count} 篇大模型训练与推理相关论文，"
            f"涵盖 {', '.join(list(categories)[:3])} 等领域。"
        )

    def execute(self, papers: List[ArXivPaper], style: str = None,
                language: str = None, title_prefix: str = None) -> GeneratorResult:
        """
        执行内容生成任务

        Args:
            papers: 论文列表
            style: 写作风格
            language: 输出语言
            title_prefix: 标题前缀

        Returns:
            GeneratorResult: 生成结果
        """
        if not papers:
            return GeneratorResult(
                success=False,
                error_message="论文列表为空，无法生成内容"
            )

        style = style or self.config["default_style"]
        title_prefix = title_prefix or self.config["title_prefix"]

        try:
            template = self.STYLE_TEMPLATES.get(style, self.STYLE_TEMPLATES["professional"])

            content_parts = [template["intro"]]

            for idx, paper in enumerate(papers, 1):
                paper_section = self._generate_paper_section(paper, idx, style)
                content_parts.append(paper_section)

            content_parts.append(template["outro"])

            today = datetime.now().strftime("%Y年%m月%d日")
            title = f"{title_prefix}{today}"

            summary = self._generate_summary(papers)
            tags = self._extract_tags(papers)

            blog_content = BlogContent(
                title=title,
                summary=summary,
                content="".join(content_parts),
                tags=tags,
                category=self.config["default_category"],
                created_at=datetime.now().isoformat(),
            )

            return GeneratorResult(success=True, blog_content=blog_content)

        except Exception as e:
            return GeneratorResult(success=False, error_message=str(e))


def generate_blog_content(papers: List[ArXivPaper],
                          style: str = "professional",
                          config: dict = None) -> GeneratorResult:
    """
    便捷函数：生成博客内容

    Args:
        papers: 论文列表
        style: 写作风格
        config: 额外配置

    Returns:
        GeneratorResult: 生成结果
    """
    generator = ContentGeneratorSkill(config)
    return generator.execute(papers=papers, style=style)
